### ISSUE TITLE
You are giving this error when downloading the songs.

### ISSUE THREAD

**Issue by WellingtonMonteiro** [Khazababa/Qobuz-DL-Node#2]
ls
Downloads  app.js       modules       package-lock.json
README.md  config.json  node_modules  package.json
$ nano config.json
$ node app.js
Enter URL: http://open.qobuz.com/track/100872775
TypeError: Cannot read property 'title' of undefined
    at download (/data/data/com.termux/files/home/Qobuz-DL-Node/modules/download.js:9:42)
    at async init (/data/data/com.termux/files/home/Qobuz-DL-Node/app.js:28:16)
$

**Comment by Khazababa** [comment]
Doesn't seem like an issue when I try to download the track from my machine.
Could you please write down your node version, platform information etc, so that I can try to recreate this error?

**Comment by WellingtonMonteiro** [comment]
Welcome to Node.js v14.8.0.
Type ".help" for more information.

**Comment by WellingtonMonteiro** [comment]
I'm using Android 9 version on termux.

**Comment by Khazababa** [comment]
It could be because of the session being invalid, I recommend removing the config.json file and trying to log in again.
Please let me know if that helps.

**Comment by WellingtonMonteiro** [comment]
cd Qobuz-DL-Node
$ ls
Downloads  app.js       modules       package-lock.json
README.md  config.json  node_modules  package.json
$ rm -rf config.json
$ ls
Downloads  app.js   node_modules       package.json
README.md  modules  package-lock.json
$ node app.js
Enter your email: http://open.qobuz.com/track/85332509
Enter your password:
Logging in, please wait...
TypeError: Cannot read property 'subscription' of undefined
    at login (/data/data/com.termux/files/home/Qobuz-DL-Node/modules/login.js:14:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getSecrets (/data/data/com.termux/files/home/Qobuz-DL-Node/modules/secrets.js:42:16)
    at async init (/data/data/com.termux/files/home/Qobuz-DL-Node/app.js:16:39)
$ node app.js
Enter your email: mayte.del@uanl.edu.mx
Enter your password: Wxm2824#$
Logging in, please wait...
Login successful!
Wrote Config file
Enter URL: http://open.qobuz.com/track/85332509
(node:17594) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'title' of undefined
    at download (/data/data/com.termux/files/home/Qobuz-DL-Node/modules/download.js:9:42)
    at async init (/data/data/com.termux/files/home/Qobuz-DL-Node/app.js:28:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17594) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17594) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
$

**Comment by WellingtonMonteiro** [comment]
Logging in, please wait...
Login successful!
Wrote Config file
Enter URL: http://open.qobuz.com/track/85332509
(node:17594) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'title' of undefined
    at download (/data/data/com.termux/files/home/Qobuz-DL-Node/modules/download.js:9:42)
    at async init (/data/data/com.termux/files/home/Qobuz-DL-Node/app.js:28:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17594) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17594) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Khazababa** [comment]
it could be because of some timezone issue, I recommend using a vpn.
Also try updating to latest version.
Also, make sure you have a studio subscription.
